swagger: '2.0'
info:
  version: "0.0.1"
  title: InterviewTemplate.Api
paths:
  /api/IncorrectAlignment:
    post:
      tags:
        - IncorrectAlignment
      summary: 'Not to implement, only to use in the second goal'
      operationId: Post
      consumes:
        - application/json-patch+json
        - application/json
        - text/json
        - application/*+json
      produces: []
      parameters:
        - name: incorrectIds
          in: body
          required: false
          schema:
            uniqueItems: false
            type: array
            items:
              format: int32
              type: integer
      responses:
        '200':
          description: Success
  /api/Manager:
    get:
      tags:
        - Manager
      operationId: Get
      consumes: []
      produces:
        - text/plain
        - application/json
        - text/json
      parameters: []
      responses:
        '200':
          description: Success
          schema:
            uniqueItems: false
            type: array
            items:
              $ref: '#/definitions/ManagerResponse'
    post:
      tags:
        - Manager
      operationId: ManagerPost
      consumes:
        - application/json-patch+json
        - application/json
        - text/json
        - application/*+json
      produces: []
      parameters:
        - name: request
          in: body
          required: false
          schema:
            $ref: '#/definitions/ManagerRequest'
      responses:
        '200':
          description: Success
  '/api/Manager/{id}':
    get:
      tags:
        - Manager
      operationId: ManagerGet
      consumes: []
      produces:
        - text/plain
        - application/json
        - text/json
      parameters:
        - name: id
          in: path
          required: true
          type: integer
          format: int32
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/ManagerResponse'
    put:
      tags:
        - Manager
      operationId: ManagerPut
      consumes:
        - application/json-patch+json
        - application/json
        - text/json
        - application/*+json
      produces: []
      parameters:
        - name: id
          in: path
          required: true
          type: integer
          format: int32
        - name: request
          in: body
          required: false
          schema:
            $ref: '#/definitions/ManagerRequest'
      responses:
        '200':
          description: Success
    delete:
      tags:
        - Manager
      operationId: ManagerDelete
      consumes: []
      produces: []
      parameters:
        - name: id
          in: path
          required: true
          type: integer
          format: int32
      responses:
        '200':
          description: Success
  /api/Match:
    get:
      tags:
        - Match
      operationId: MatchGetAll
      consumes: []
      produces:
        - text/plain
        - application/json
        - text/json
      parameters: []
      responses:
        '200':
          description: Success
          schema:
            uniqueItems: false
            type: array
            items:
              $ref: '#/definitions/MatchResponse'
    post:
      tags:
        - Match
      operationId: MatchPost
      consumes:
        - application/json-patch+json
        - application/json
        - text/json
        - application/*+json
      produces: []
      parameters:
        - name: request
          in: body
          required: false
          schema:
            $ref: '#/definitions/MatchRequest'
      responses:
        '200':
          description: Success
  '/api/Match/{id}':
    get:
      tags:
        - Match
      operationId: MatchGet
      consumes: []
      produces:
        - text/plain
        - application/json
        - text/json
      parameters:
        - name: id
          in: path
          required: true
          type: integer
          format: int32
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/MatchResponse'
    put:
      tags:
        - Match
      operationId: MatchPut
      consumes:
        - application/json-patch+json
        - application/json
        - text/json
        - application/*+json
      produces: []
      parameters:
        - name: id
          in: path
          required: true
          type: integer
          format: int32
        - name: request
          in: body
          required: false
          schema:
            $ref: '#/definitions/MatchRequest'
      responses:
        '200':
          description: Success
    delete:
      tags:
        - Match
      operationId: MatchDelete
      consumes: []
      produces: []
      parameters:
        - name: id
          in: path
          required: true
          type: integer
          format: int32
      responses:
        '200':
          description: Success
  /api/Player:
    get:
      tags:
        - Player
      operationId: PlayerGetAll
      consumes: []
      produces:
        - text/plain
        - application/json
        - text/json
      parameters: []
      responses:
        '200':
          description: Success
          schema:
            uniqueItems: false
            type: array
            items:
              $ref: '#/definitions/PlayerResponse'
    post:
      tags:
        - Player
      operationId: PlayerPost
      consumes:
        - application/json-patch+json
        - application/json
        - text/json
        - application/*+json
      produces: []
      parameters:
        - name: request
          in: body
          required: false
          schema:
            $ref: '#/definitions/PlayerRequest'
      responses:
        '200':
          description: Success
  '/api/Player/{id}':
    get:
      tags:
        - Player
      operationId: PlayerGet
      consumes: []
      produces:
        - text/plain
        - application/json
        - text/json
      parameters:
        - name: id
          in: path
          required: true
          type: integer
          format: int32
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/PlayerResponse'
    put:
      tags:
        - Player
      operationId: PlayerPut
      consumes:
        - application/json-patch+json
        - application/json
        - text/json
        - application/*+json
      produces: []
      parameters:
        - name: id
          in: path
          required: true
          type: integer
          format: int32
        - name: request
          in: body
          required: false
          schema:
            $ref: '#/definitions/PlayerRequest'
      responses:
        '200':
          description: Success
    delete:
      tags:
        - Player
      operationId: PlayerDelete
      consumes: []
      produces: []
      parameters:
        - name: id
          in: path
          required: true
          type: integer
          format: int32
      responses:
        '200':
          description: Success
  /api/Referee:
    get:
      tags:
        - Referee
      operationId: RefereeGetAll
      consumes: []
      produces:
        - text/plain
        - application/json
        - text/json
      parameters: []
      responses:
        '200':
          description: Success
          schema:
            uniqueItems: false
            type: array
            items:
              $ref: '#/definitions/RefereeResponse'
    post:
      tags:
        - Referee
      operationId: RefereePost
      consumes:
        - application/json-patch+json
        - application/json
        - text/json
        - application/*+json
      produces: []
      parameters:
        - name: request
          in: body
          required: false
          schema:
            $ref: '#/definitions/RefereeRequest'
      responses:
        '200':
          description: Success
  '/api/Referee/{id}':
    get:
      tags:
        - Referee
      operationId: RefereeGet
      consumes: []
      produces:
        - text/plain
        - application/json
        - text/json
      parameters:
        - name: id
          in: path
          required: true
          type: integer
          format: int32
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/RefereeResponse'
    put:
      tags:
        - Referee
      operationId: RefereePut
      consumes:
        - application/json-patch+json
        - application/json
        - text/json
        - application/*+json
      produces: []
      parameters:
        - name: id
          in: path
          required: true
          type: integer
          format: int32
        - name: request
          in: body
          required: false
          schema:
            $ref: '#/definitions/RefereeRequest'
      responses:
        '200':
          description: Success
    delete:
      tags:
        - Referee
      operationId: RefereeDelete
      consumes: []
      produces: []
      parameters:
        - name: id
          in: path
          required: true
          type: integer
          format: int32
      responses:
        '200':
          description: Success
  /api/Statistics/yellowcards:
    get:
      tags:
        - Statistics
      operationId: GetStatisticsYellowCards
      consumes: []
      produces:
        - text/plain
        - application/json
        - text/json
      parameters: []
      responses:
        '200':
          description: Success
          schema:
            uniqueItems: false
            type: array
            items:
              $ref: '#/definitions/CardResponse'
  /api/Statistics/redcards:
    get:
      tags:
        - Statistics
      operationId: GetStatisticsRedCards
      consumes: []
      produces:
        - text/plain
        - application/json
        - text/json
      parameters: []
      responses:
        '200':
          description: Success
          schema:
            uniqueItems: false
            type: array
            items:
              $ref: '#/definitions/CardResponse'
  /api/Statistics/minutes:
    get:
      tags:
        - Statistics
      operationId: GetStatisticsMinutes
      consumes: []
      produces:
        - text/plain
        - application/json
        - text/json
      parameters: []
      responses:
        '200':
          description: Success
          schema:
            uniqueItems: false
            type: array
            items:
              $ref: '#/definitions/MinuteResponse'
definitions:
  ManagerResponse:
    type: object
    properties:
      name:
        type: string
      id:
        format: int32
        type: integer
      teamName:
        type: string
      yellowCards:
        format: int32
        type: integer
      redCards:
        format: int32
        type: integer
  ManagerRequest:
    type: object
    properties:
      name:
        type: string
      teamName:
        type: string
      yellowCards:
        format: int32
        type: integer
      redCards:
        format: int32
        type: integer
  MatchResponse:
    type: object
    properties:
      name:
        type: string
      houseTeamPlayers:
        uniqueItems: false
        type: array
        items:
          $ref: '#/definitions/PlayerResponse'
      awayTeamPlayers:
        uniqueItems: false
        type: array
        items:
          $ref: '#/definitions/PlayerResponse'
      houseTeamManager:
        $ref: '#/definitions/ManagerResponse'
      awayTeamManager:
        $ref: '#/definitions/ManagerResponse'
      referee:
        $ref: '#/definitions/RefereeResponse'
      date:
        format: date-time
        type: string
  PlayerResponse:
    type: object
    properties:
      name:
        type: string
      id:
        format: int32
        type: integer
      number:
        format: int32
        type: integer
      teamName:
        type: string
      yellowCards:
        format: int32
        type: integer
      redCards:
        format: int32
        type: integer
      minutesPlayed:
        format: int32
        type: integer
  RefereeResponse:
    type: object
    properties:
      name:
        type: string
      id:
        format: int32
        type: integer
      minutesPlayed:
        format: int32
        type: integer
  MatchRequest:
    type: object
    properties:
      name:
        type: string
      houseTeam:
        uniqueItems: false
        type: array
        items:
          format: int32
          type: integer
      awayTeam:
        uniqueItems: false
        type: array
        items:
          format: int32
          type: integer
      houseManagerId:
        format: int32
        type: integer
      awayManagerId:
        format: int32
        type: integer
      referee:
        format: int32
        type: integer
      date:
        format: date-time
        type: string
  PlayerRequest:
    type: object
    properties:
      name:
        type: string
      number:
        format: int32
        type: integer
      teamName:
        type: string
      yellowCards:
        format: int32
        type: integer
      redCards:
        format: int32
        type: integer
      minutesPlayed:
        format: int32
        type: integer
  RefereeRequest:
    type: object
    properties:
      name:
        type: string
      minutesPlayed:
        format: int32
        type: integer
  CardResponse:
    type: object
    properties:
      name:
        type: string
      id:
        format: int32
        type: integer
      teamName:
        type: string
      total:
        format: int32
        type: integer
  MinuteResponse:
    type: object
    properties:
      name:
        type: string
      id:
        format: int32
        type: integer
      total:
        format: int32
        type: integer